### ISSUE TITLE
Next.js PWA example

### ISSUE THREAD

**Issue by prateekrastogi** [codebusking/next-hnpwa-guide-kit#7]
Hi,
Glad to see that you managed to meet all the PWA requirements using next.js and workbox. Would you be open to create an example focused on PWA integration with next.js? 
If you can create such example and create a pull request to add it in official next.js examples repo, i guess, it would help lot of people trying to do PWA with next.js. Looking at the your codebase, it feels that it will require very few modifications  for pull request to be accepted on next.js official repo. But, I am not sure about the missing production features you mentioned.
Thank you.

**Comment by ragingwind** [comment]
Thanks. I'm already working on another project for PRs with PWA. Please, wait for it

**Comment by prateekrastogi** [comment]
Will definitely try that out. Thank you.
